@login = http://localhost:3000/user/login
@singup = http://localhost:3000/user/usersp

@addmaterias = http://localhost:3000/user/addMateria

@cursarmaterias = http://localhost:3000/user/cursar

@materiabyid = http://localhost:3000/user/getMateriaByid



POST {{login}}
Content-Type: application/json

{
   "dni" : "2023",
   "password": "1234"
}

###
POST {{singup}}
Content-Type: application/json

{
   "dni" : "2022",
   "nombre" : "prueba 1",
   "password" : "1234"
}

###
POST {{addmaterias}}
Content-Type: application/json

{
    "nombre_materia": "Matematicas"
}

###
POST {{cursarmaterias}}
Content-Type: application/json

{
    "dni": "2022",
    "id_m": "1"
}

###
GET {{materiabyid}}
Content-Type: application/json

{
    "id": "10",
}